import type { KnownProviderId } from "./types";

export type ProviderCategory = "api" | "coding" | "search" | "social" | "cloud" | "inference";

export interface ProviderMeta {
  id: KnownProviderId;
  label: string;
  category: ProviderCategory;
  featured: boolean;
  // UI color for card background — Tailwind class fragments.
  color: string;
  // Where a user goes to see their usage on the provider side.
  dashboardUrl: string;
  dashboardLabel: string;
  // Copy shown in "Easy entry" mode.
  usageHint: string;
  // Whether we can pull usage from an API key of theirs.
  apiKeySupported: boolean;
  apiKeyHint?: string;
  apiKeyLink?: { url: string; label: string };
  // Whether this provider has any tier subscription entries (see tiers.ts).
  hasTiers?: boolean;
}

// Every AI service EcoDues knows how to categorize. Featured providers get
// their own card in onboarding. Everything else lives in the "See all providers"
// drawer plus the "Other AI service" freeform escape hatch.
export const PROVIDER_CATALOG: ProviderMeta[] = [
  // ── FEATURED (surfaced on the main connect UI) ─────────────────────────
  {
    id: "openai",
    label: "OpenAI / ChatGPT",
    category: "api",
    featured: true,
    color: "bg-green-50 border-green-200 dark:bg-green-950/40 dark:border-green-900/60",
    dashboardUrl: "https://platform.openai.com/usage",
    dashboardLabel: "platform.openai.com/usage",
    usageHint: "Shows your monthly spend broken down by model. Copy the total or paste the whole page.",
    apiKeySupported: true,
    apiKeyHint: "Requires an Admin API key (sk-admin-…), NOT a regular API key. We use it to pull org-wide usage.",
    apiKeyLink: { url: "https://platform.openai.com/settings/organization/admin-keys", label: "Create admin key" },
    hasTiers: true,
  },
  {
    id: "anthropic",
    label: "Anthropic / Claude",
    category: "api",
    featured: true,
    color: "bg-orange-50 border-orange-200 dark:bg-orange-950/40 dark:border-orange-900/60",
    dashboardUrl: "https://console.anthropic.com/settings/billing",
    dashboardLabel: "console.anthropic.com/settings/billing",
    usageHint: "Go to Billing → Usage. Shows token counts and cost by model per month.",
    apiKeySupported: true,
    apiKeyHint: "Requires an Admin API key (sk-ant-admin01-…). Regular API keys don't have usage-report access.",
    apiKeyLink: { url: "https://console.anthropic.com/settings/admin-keys", label: "Create admin key" },
    hasTiers: true,
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    category: "api",
    featured: true,
    color: "bg-violet-50 border-violet-200 dark:bg-violet-950/40 dark:border-violet-900/60",
    dashboardUrl: "https://openrouter.ai/credits",
    dashboardLabel: "openrouter.ai/credits",
    usageHint: "Click your avatar → Activity. You'll see credits used per day and model.",
    apiKeySupported: true,
    apiKeyHint: "OpenRouter API key — we'll pull your usage automatically each month.",
    apiKeyLink: { url: "https://openrouter.ai/keys", label: "openrouter.ai/keys" },
  },
  {
    id: "gemini",
    label: "Google Gemini",
    category: "api",
    featured: true,
    color: "bg-blue-50 border-blue-200 dark:bg-blue-950/40 dark:border-blue-900/60",
    dashboardUrl: "https://aistudio.google.com/billing",
    dashboardLabel: "aistudio.google.com/billing",
    usageHint: "Open AI Studio → Settings → Billing, or check Google Cloud console for API usage costs.",
    apiKeySupported: false,
    apiKeyHint: "Google doesn't expose a per-project usage API — please log Gemini usage via Easy entry, Paste & parse, or your subscription tier.",
    hasTiers: true,
  },

  // ── CODING ASSISTANTS ─────────────────────────────────────────────────
  {
    id: "github_copilot",
    label: "GitHub Copilot",
    category: "coding",
    featured: false,
    color: "bg-slate-50 border-slate-200 dark:bg-slate-900/50 dark:border-slate-800",
    dashboardUrl: "https://github.com/settings/copilot",
    dashboardLabel: "github.com/settings/copilot",
    usageHint: "Copilot doesn't publish per-user token counts — pick your plan and we'll estimate.",
    apiKeySupported: false,
    hasTiers: true,
  },
  {
    id: "cursor",
    label: "Cursor",
    category: "coding",
    featured: false,
    color: "bg-neutral-50 border-neutral-200 dark:bg-neutral-900/50 dark:border-neutral-800",
    dashboardUrl: "https://www.cursor.com/settings",
    dashboardLabel: "cursor.com/settings",
    usageHint: "Cursor shows monthly requests but not tokens. Pick your plan or paste the numbers.",
    apiKeySupported: false,
    hasTiers: true,
  },
  {
    id: "windsurf",
    label: "Windsurf (Codeium)",
    category: "coding",
    featured: false,
    color: "bg-cyan-50 border-cyan-200 dark:bg-cyan-950/40 dark:border-cyan-900/60",
    dashboardUrl: "https://codeium.com/account",
    dashboardLabel: "codeium.com/account",
    usageHint: "Windsurf/Codeium usage lives in your account dashboard. Pick your plan for an estimate.",
    apiKeySupported: false,
    hasTiers: true,
  },
  {
    id: "replit_ai",
    label: "Replit AI",
    category: "coding",
    featured: false,
    color: "bg-orange-50 border-orange-200 dark:bg-orange-950/40 dark:border-orange-900/60",
    dashboardUrl: "https://replit.com/account",
    dashboardLabel: "replit.com/account",
    usageHint: "Replit AI is bundled into Core/Teams. Pick your plan for an estimate.",
    apiKeySupported: false,
    hasTiers: true,
  },
  {
    id: "v0",
    label: "v0 by Vercel",
    category: "coding",
    featured: false,
    color: "bg-neutral-50 border-neutral-200 dark:bg-neutral-900/50 dark:border-neutral-800",
    dashboardUrl: "https://v0.dev/settings/billing",
    dashboardLabel: "v0.dev/settings/billing",
    usageHint: "v0 tracks credits, not tokens — pick your plan for a rough estimate.",
    apiKeySupported: false,
    hasTiers: true,
  },

  // ── SEARCH & ASSISTANTS ───────────────────────────────────────────────
  {
    id: "perplexity",
    label: "Perplexity",
    category: "search",
    featured: false,
    color: "bg-teal-50 border-teal-200 dark:bg-teal-950/40 dark:border-teal-900/60",
    dashboardUrl: "https://www.perplexity.ai/settings/account",
    dashboardLabel: "perplexity.ai/settings",
    usageHint: "Perplexity doesn't publish per-user tokens — pick your plan for an estimate.",
    apiKeySupported: false,
    hasTiers: true,
  },
  {
    id: "poe",
    label: "Poe",
    category: "search",
    featured: false,
    color: "bg-purple-50 border-purple-200 dark:bg-purple-950/40 dark:border-purple-900/60",
    dashboardUrl: "https://poe.com/settings/subscription",
    dashboardLabel: "poe.com/settings",
    usageHint: "Poe uses opaque credits across many models. Pick your plan for an average.",
    apiKeySupported: false,
    hasTiers: true,
  },
  {
    id: "kagi",
    label: "Kagi",
    category: "search",
    featured: false,
    color: "bg-yellow-50 border-yellow-200 dark:bg-yellow-950/40 dark:border-yellow-900/60",
    dashboardUrl: "https://kagi.com/settings",
    dashboardLabel: "kagi.com/settings",
    usageHint: "Kagi Ultimate includes The Assistant. Pick that tier if you subscribe.",
    apiKeySupported: false,
    hasTiers: true,
  },
  {
    id: "you",
    label: "You.com",
    category: "search",
    featured: false,
    color: "bg-sky-50 border-sky-200 dark:bg-sky-950/40 dark:border-sky-900/60",
    dashboardUrl: "https://you.com/settings",
    dashboardLabel: "you.com/settings",
    usageHint: "You.com bundles multiple models — pick the Pro plan for an estimate.",
    apiKeySupported: false,
    hasTiers: true,
  },

  // ── SOCIAL / CONSUMER ─────────────────────────────────────────────────
  {
    id: "grok",
    label: "Grok (X / xAI)",
    category: "social",
    featured: false,
    color: "bg-neutral-50 border-neutral-200 dark:bg-neutral-900/50 dark:border-neutral-800",
    dashboardUrl: "https://x.com/i/premium_sign_up",
    dashboardLabel: "x.com premium",
    usageHint: "Grok comes bundled with X Premium. Pick your tier.",
    apiKeySupported: false,
    hasTiers: true,
  },
  {
    id: "meta_ai",
    label: "Meta AI",
    category: "social",
    featured: false,
    color: "bg-blue-50 border-blue-200 dark:bg-blue-950/40 dark:border-blue-900/60",
    dashboardUrl: "https://ai.meta.com",
    dashboardLabel: "ai.meta.com",
    usageHint: "Meta AI is free across WhatsApp / Instagram / Messenger — pick the free tier for a baseline.",
    apiKeySupported: false,
    hasTiers: true,
  },
  {
    id: "character_ai",
    label: "Character.ai",
    category: "social",
    featured: false,
    color: "bg-pink-50 border-pink-200 dark:bg-pink-950/40 dark:border-pink-900/60",
    dashboardUrl: "https://beta.character.ai/subscription",
    dashboardLabel: "character.ai subscription",
    usageHint: "Character.ai doesn't publish token counts — pick your plan for an estimate.",
    apiKeySupported: false,
    hasTiers: true,
  },

  // ── INFERENCE-AS-A-SERVICE (API key exists, no reliable usage endpoint) ─
  {
    id: "groq",
    label: "Groq Cloud",
    category: "inference",
    featured: false,
    color: "bg-red-50 border-red-200 dark:bg-red-950/40 dark:border-red-900/60",
    dashboardUrl: "https://console.groq.com/settings/usage",
    dashboardLabel: "console.groq.com",
    usageHint: "Groq shows usage in-console. Copy the totals into Easy entry.",
    apiKeySupported: false,
  },
  {
    id: "together",
    label: "Together AI",
    category: "inference",
    featured: false,
    color: "bg-indigo-50 border-indigo-200 dark:bg-indigo-950/40 dark:border-indigo-900/60",
    dashboardUrl: "https://api.together.xyz/settings/billing",
    dashboardLabel: "api.together.xyz",
    usageHint: "Together shows monthly spend + tokens under Billing.",
    apiKeySupported: false,
  },
  {
    id: "fireworks",
    label: "Fireworks AI",
    category: "inference",
    featured: false,
    color: "bg-amber-50 border-amber-200 dark:bg-amber-950/40 dark:border-amber-900/60",
    dashboardUrl: "https://fireworks.ai/account/billing",
    dashboardLabel: "fireworks.ai/account",
    usageHint: "Fireworks tracks usage per model in-console. Paste or type the totals.",
    apiKeySupported: false,
  },
  {
    id: "deepseek",
    label: "DeepSeek",
    category: "inference",
    featured: false,
    color: "bg-blue-50 border-blue-200 dark:bg-blue-950/40 dark:border-blue-900/60",
    dashboardUrl: "https://platform.deepseek.com/usage",
    dashboardLabel: "platform.deepseek.com",
    usageHint: "DeepSeek shows monthly totals under Usage. Copy them in.",
    apiKeySupported: false,
  },
  {
    id: "mistral",
    label: "Mistral La Plateforme",
    category: "inference",
    featured: false,
    color: "bg-orange-50 border-orange-200 dark:bg-orange-950/40 dark:border-orange-900/60",
    dashboardUrl: "https://console.mistral.ai/usage/",
    dashboardLabel: "console.mistral.ai",
    usageHint: "Mistral shows usage under Console → Usage.",
    apiKeySupported: false,
  },
  {
    id: "cohere",
    label: "Cohere",
    category: "inference",
    featured: false,
    color: "bg-fuchsia-50 border-fuchsia-200 dark:bg-fuchsia-950/40 dark:border-fuchsia-900/60",
    dashboardUrl: "https://dashboard.cohere.com/billing/usage",
    dashboardLabel: "dashboard.cohere.com",
    usageHint: "Cohere dashboard has a Usage tab with per-model breakdowns.",
    apiKeySupported: false,
  },
  {
    id: "xai_api",
    label: "xAI API (Grok API)",
    category: "inference",
    featured: false,
    color: "bg-neutral-50 border-neutral-200 dark:bg-neutral-900/50 dark:border-neutral-800",
    dashboardUrl: "https://console.x.ai",
    dashboardLabel: "console.x.ai",
    usageHint: "xAI's console shows usage under Billing.",
    apiKeySupported: false,
  },
  {
    id: "replicate",
    label: "Replicate",
    category: "inference",
    featured: false,
    color: "bg-black/5 border-black/10 dark:bg-white/5 dark:border-white/10",
    dashboardUrl: "https://replicate.com/account/billing",
    dashboardLabel: "replicate.com/account",
    usageHint: "Replicate bills by prediction seconds. Paste the monthly total.",
    apiKeySupported: false,
  },
  {
    id: "fal",
    label: "Fal.ai",
    category: "inference",
    featured: false,
    color: "bg-purple-50 border-purple-200 dark:bg-purple-950/40 dark:border-purple-900/60",
    dashboardUrl: "https://fal.ai/dashboard/billing",
    dashboardLabel: "fal.ai/dashboard",
    usageHint: "Fal.ai bills per compute-second. Paste your monthly spend.",
    apiKeySupported: false,
  },
  {
    id: "huggingface",
    label: "HuggingFace Inference",
    category: "inference",
    featured: false,
    color: "bg-yellow-50 border-yellow-200 dark:bg-yellow-950/40 dark:border-yellow-900/60",
    dashboardUrl: "https://huggingface.co/settings/billing",
    dashboardLabel: "huggingface.co/settings",
    usageHint: "HF shows inference-endpoint usage under Billing.",
    apiKeySupported: false,
  },
  {
    id: "cerebras",
    label: "Cerebras Inference",
    category: "inference",
    featured: false,
    color: "bg-red-50 border-red-200 dark:bg-red-950/40 dark:border-red-900/60",
    dashboardUrl: "https://cloud.cerebras.ai/",
    dashboardLabel: "cloud.cerebras.ai",
    usageHint: "Cerebras shows token counts + spend in the console dashboard.",
    apiKeySupported: false,
  },
  {
    id: "sambanova",
    label: "SambaNova Cloud",
    category: "inference",
    featured: false,
    color: "bg-emerald-50 border-emerald-200 dark:bg-emerald-950/40 dark:border-emerald-900/60",
    dashboardUrl: "https://cloud.sambanova.ai/",
    dashboardLabel: "cloud.sambanova.ai",
    usageHint: "SambaNova shows usage per model in-console.",
    apiKeySupported: false,
  },

  // ── HYPERSCALER CLOUD ─────────────────────────────────────────────────
  {
    id: "vertex_ai",
    label: "Google Vertex AI",
    category: "cloud",
    featured: false,
    color: "bg-blue-50 border-blue-200 dark:bg-blue-950/40 dark:border-blue-900/60",
    dashboardUrl: "https://console.cloud.google.com/billing",
    dashboardLabel: "GCP Billing",
    usageHint: "Vertex usage lives in GCP Billing. Filter by AI Platform / Vertex AI SKUs and paste the totals.",
    apiKeySupported: false,
  },
  {
    id: "azure_openai",
    label: "Azure OpenAI",
    category: "cloud",
    featured: false,
    color: "bg-sky-50 border-sky-200 dark:bg-sky-950/40 dark:border-sky-900/60",
    dashboardUrl: "https://portal.azure.com/#view/Microsoft_Azure_CostManagement",
    dashboardLabel: "Azure Cost Management",
    usageHint: "Azure OpenAI spend appears under Cost Management. Filter by 'Azure OpenAI' service.",
    apiKeySupported: false,
  },
  {
    id: "aws_bedrock",
    label: "AWS Bedrock",
    category: "cloud",
    featured: false,
    color: "bg-amber-50 border-amber-200 dark:bg-amber-950/40 dark:border-amber-900/60",
    dashboardUrl: "https://console.aws.amazon.com/billing",
    dashboardLabel: "AWS Billing",
    usageHint: "Bedrock invocations show up in AWS Billing under 'Amazon Bedrock'.",
    apiKeySupported: false,
  },
  {
    id: "ibm_watsonx",
    label: "IBM watsonx",
    category: "cloud",
    featured: false,
    color: "bg-slate-50 border-slate-200 dark:bg-slate-900/50 dark:border-slate-800",
    dashboardUrl: "https://dataplatform.cloud.ibm.com/usage",
    dashboardLabel: "watsonx usage",
    usageHint: "watsonx bills capacity units. Paste your monthly total or spend.",
    apiKeySupported: false,
  },

  // ── PRODUCTIVITY / ENTERPRISE ─────────────────────────────────────────
  {
    id: "microsoft_copilot",
    label: "Microsoft 365 Copilot",
    category: "coding",
    featured: false,
    color: "bg-sky-50 border-sky-200 dark:bg-sky-950/40 dark:border-sky-900/60",
    dashboardUrl: "https://admin.microsoft.com/Adminportal/Home#/copilot",
    dashboardLabel: "Microsoft 365 admin",
    usageHint: "M365 Copilot bundles GPT-4o into Word, Excel, Outlook, Teams. Pick your plan for an estimate.",
    apiKeySupported: false,
    hasTiers: true,
  },
  {
    id: "notion_ai",
    label: "Notion AI",
    category: "coding",
    featured: false,
    color: "bg-neutral-50 border-neutral-200 dark:bg-neutral-900/50 dark:border-neutral-800",
    dashboardUrl: "https://www.notion.so/billing",
    dashboardLabel: "notion.so/billing",
    usageHint: "Notion AI is bundled into paid plans. Pick your plan for an estimate.",
    apiKeySupported: false,
    hasTiers: true,
  },

  // ── Freeform catch-all ─────────────────────────────────────────────────
  {
    id: "other",
    label: "Other / custom",
    category: "inference",
    featured: false,
    color: "bg-muted border-border",
    dashboardUrl: "https://github.com/gitJamoo/ecodues/issues",
    dashboardLabel: "Request a provider",
    usageHint: "Any AI service not listed above — type a name and paste your usage.",
    apiKeySupported: false,
  },
];

export const providerById = (id: string): ProviderMeta | undefined =>
  PROVIDER_CATALOG.find((p) => p.id === id);

export const featuredProviders = PROVIDER_CATALOG.filter((p) => p.featured);
export const otherProviders = PROVIDER_CATALOG.filter((p) => !p.featured && p.id !== "other");
